### PR TITLE
Clean up allocator for gcc 5.3

### PR DESCRIPTION
**Pull request by jacquelinekay**
Connects to #37

**Do not merge until we update to Xenial; this will break the build with the default gcc on Trusty.**

### CODE REVIEW

**Comment by jacquelinekay** [comment]
[Build Status](http://ci.ros2.org/job/ci_linux/1411/)

**Comment by dirk-thomas** [comment]
Should the branch name be changed to `xenial` so that the patch can be tested together with all the other changes?

**Comment by jacquelinekay** [comment]
ok, I've opened a branch named "xenial" which is even with this one:

https://github.com/ros2/realtime_support/tree/xenial

Would you like me to reopen the pull request with that branch and close this one?

(Same goes for ros2/examples#109)

**Comment by dirk-thomas** [comment]
It's fine by me to keep this one. But now we can try all patches together and see what is still missing.

**Comment by dirk-thomas** [comment]
I also deleted the xenial branch.

**Pull request merged**
