### PR TITLE
fix memory management of rttest_sample_buffer

### LINKED ISSUE #21: memory corruption
The `Rttest` class stores pointers to custom allocated memory but does neither implement a correct copy constructor nor assignment operator (https://github.com/ros2/realtime_support/blob/master/rttest/src/rttest.cpp#L41-L57). These results in random segfaults.

### PR DESCRIPTION
**Pull request by dirk-thomas**
Connect to #21.

http://ci.ros2.org/job/ci_linux/817/

### CODE REVIEW

**Comment by jacquelinekay** [comment]
Does this fix the segfault with FastRTPS?

This package and the demo that uses it only builds on Linux. So you should launch a Linux CI job for it.

**Comment by jacquelinekay** [comment]
http://ci.ros2.org/job/ci_linux/817/testReport/(root)/pendulum_control/test_demo_pendulum__rmw_fastrtps_cpp_xunit_missing_result/

It looks like the test still doesn't succeed...? I don't have FastRTPS set up here so I can't test it myself. If it would help you I can try to set up a FastRTPS build.

The changes look good, I'm just not sure it's fixing the original issue you ran into.

**Comment by wjwwood** [comment]
lgtm

**Comment by gerkey** [comment]
+1

**Comment by dirk-thomas** [comment]
As far as I can see the test runs without a segfault. Only the output matching fails to find the expected content since it lacks the FastRTPS specific stuff.

**Comment by gerkey** [comment]
We'll fix up the output-matching for FastRTPS in all the tests soon enough.

**Pull request merged**
